# -*- coding: utf-8 -*-
"""Trabajo_Practico_1_Introducción_a_Python_parte_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJIPdVcLYqtv0s5rKPy5Uud2ABAEXlkN

# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Taller de Python: Parte 1** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En estos ejercicios vamos a trabajar cosas que nos permitan empezar a programar usando Python. 

La idea es que ustedes vayan resolviendo los ejercicios sin la necesidad de instalarse nada en sus computadoras. 
Antes que nada, creen una copia de este archivo en su ***Google Drive*** para tener permisos de edición, luego pueden compartirlo con quien quieran, tengan cuidado con los permisos al momento de compartir!!!!!!!. Si quieren, nos pueden compartir su documento para que ayudemos con las dudas.

### **sergio.gonzalez@unahur.edu.ar** ###
### **martin.pustilnik@unahur.edu.ar** ###

En los bloques de código como el que les aparece aca abajo, se puede programar en Python, al pararse dentro del bloque, aparecerá un ícono de "*play*" en la esquina superior izquierda, "*clickeando*" en este ícono, se ejecuta el código escrito y se muestra la salida debajo, probemos:
"""

print("hola")

precio = "20"
#print(type(precio))
precioEntero = int(precio)
#print(type(precioEntero))

cantidad = 5

precioTotal = precioEntero * cantidad

print("Precio =" , precio , precioEntero, cantidad, "precio Total =" , precioTotal)

variableDestino = input("Ingrese un numero: ")

print(type(variableDestino))
print(variableDestino)

"""Una cosa a tener en cuenta es que todos los bloques de código estan conectados entre sí, es por eso que si vemos en el bloque de código de abajo, podemos usar la variable "precio" declarada en el bloque anterior, veamos un ejemplo:"""

#precioConIVA = 1.21*precio
#print(precioConIVA)

varString = input("ingrese un nro ")
varInt = int(input("ingrese un nro "))

print(varString + varString)
print(varInt + varInt)
print(varInt + varString)

"""Ahora si, luego de las aclaraciones del caso y sabiendo como escribir y ejecutar código en los bloques de este archivo, empezamos con la guía.

#**Primera parte: Declaración de variables y operaciones básicas**

### **Ejercicio 1**

Primer programa en Python. Escribir un programa que imprima por pantalla "Hola mundo".
"""

print("Hola Mundo")

"""### **Ejercicio 2**

Escribir un programa que cargue en una variable la cadena de caracteres “Hola mundo” y luego la imprima por pantalla. 
"""

primerVariable = "Hola Mundo"
print(primerVariable)

"""### **Ejercicio 3**

Escribir un programa que cree dos variables enteras, le cargue números arbitrarios (cualquiera) y muestre por pantalla: la suma, la resta, la multiplicación, la división entera y el resto de la división entera.
"""

primerNumero = 5
segundoNumero = 6

print(primerNumero + segundoNumero)
print(primerNumero - segundoNumero)
print(primerNumero * segundoNumero)
print(primerNumero / segundoNumero)
print(primerNumero % segundoNumero)

"""### **Ejercicio 4**

Implementar algoritmos que permitan:


*   Calcular el perímetro y el área de un rectángulo, dada su base y su altura
*   Calcular el perímetro y el área de un círculo dado su radio.

Declarar las variables necesarias y asignarle números arbitrarios
"""

base = 3
altura = 5
lado1 = 5
lado2 = 5

print("área del rectángulo=", (base * altura) / 2)
print("perimetro del rectángulo=", (base + lado1 + lado2))

"""### **Ejercicio 5**

Escribir un programa que pida una temperatura en grados Celsius al usuario, realice la transformación de grados Celsius a Fahrenheit e imprima el resultado por pantalla. 
"""

temperaturaCelcius = int(input("Ingrese una temperatura en Celsius= "))
temperaturaFahrenheit = (temperaturaCelcius * 9/5) + 32
print("temperaturaFahrenheit=", temperaturaFahrenheit)

"""### **Ejercicio 6**

Escribir un programa que pregunte al usuario por el número de horas trabajadas y el costo por hora. Después debe mostrar por pantalla el sueldo que le corresponde.
"""

horasTrabajadas = int(input("Cantidad de horas trabajadas="))
costoPorHora = int(input("Costo por horas trabajadas="))
print("Sueldo correspondiente=", horasTrabajadas * costoPorHora)

"""### **Ejercicio 7**

Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable. Luego debe muestrar por pantalla la frase: "Tu índice de masa corporal es: \<imc>". Donde \<imc> es el índice de masa corporal calculado.
"""

pesoEnKg = int(input("Ingrese su peso en KG= "))
estaturaEnMetros = int(input("Ingrese su estatura en metros= "))
indiceDeMasaCorporal = pesoEnKg / estaturaEnMetros**2
print("Tu indice de masa corporal es: ", indiceDeMasaCorporal)

"""### **Ejercicio 8**

Escribir un programa que pregunte al usuario una cantidad a invertir, el interés anual y el número de años, y muestre por pantalla el capital obtenido en la inversión.
"""

cantidadAInvertir = int(input("Ingrese una cantidad a invertir= "))
interesAnual = int(input("Ingrese el interes anual= "))
numeroDeAños = int(input("Ingrese el numero de años= "))
capitalObtenidoPorInversion = 
print("Capital obtenido por inversion= ")

"""### **Ejercicio 9**

Escribir un programa que pregunte el nombre completo del usuario en la consola y después muestre por pantalla el nombre completo del usuario tres veces, una con todas las letras minúsculas, otra con todas las letras mayúsculas y otra solo con la primera letra del nombre y de los apellidos en mayúscula. El usuario puede introducir su nombre combinando mayúsculas y minúsculas como quiera.
"""

nombreUsuario = input("Ingrese su nombre completo= ")
print(nombreUsuario.lower())
print(nombreUsuario.upper())
print(nombreUsuario.title())

"""### **Ejercicio 10**

Escribir un programa que pregunte el nombre del usuario en la consola y después de que el usuario lo introduzca muestre por pantalla: "El \<NOMBRE> tiene \<N> letras", donde \<NOMBRE> es el nombre de usuario en mayúsculas y \<N> es el número de letras que tienen el nombre.
"""

nombreDeUsuario = input("Introduzca su usuario: ").upper()
print("El nombre", nombreDeUsuario, "tiene", len(nombreDeUsuario), "letras.")

"""### **Ejercicio 11**

Escribir un programa que pida una palabra al usuario, reeplace todas las letras "a" por "z" y muestre el resultado por pantalla.
"""

palabra = input("Introduzca una palabra: ").lower()
print(palabra.replace('a', 'z'))

"""### **Ejercicio 12**

Escribir un programa que pida dos palabras al usuario y muestre por pantalla la concatenacion de ambas.  
"""

palabra1 = input("Ingresa una palabra:")
palabra2 = input("Ingresa otra palabra:")

print(palabra1 + palabra2)

"""### **Ejercicio 13**

Escribir un programa que pida una palabra y un número N al usuario y muestre por pantalla la palabra ingresada repetida N veces.
"""

palabra = input("Introduzca una palabra: ")
número = int(input("Introduzca un número: "))

print(número * palabra)

"""#**Segunda parte: Estructuras de control**"""



"""### **Ejercicio 14**

Escribir un programa que pregunte al usuario su edad y muestre por pantalla si es mayor de edad o no.
"""



"""### **Ejercicio 15**

Escribir un programa que almacene la cadena de caracteres "contraseña" en una variable, pregunte al usuario por la contraseña e imprima por pantalla si la contraseña introducida por el usuario coincide con la guardada en la variable sin tener en cuenta mayúsculas y minúsculas.
"""



"""### **Ejercicio 15**

Escribir un programa pida al usuario dos números enteros e informe por pantalla cual es menor de los dos, si son iguales, indicarlo por separado.

"""



"""### **Ejercicio 16**

Escribir un programa que pida al usuario un número entero e indique si dicho número es par o impar.
"""



"""###**Ejercicio 17**

Para pagar un determinado impuesto se debe ser mayor de 18 años y tener unos ingresos iguales o superiores a $100000 mensuales. Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que pagar o no.
"""



"""### **Ejercicio 18**

Escribir un programa que pida al usuario un número entero del 1 al 7 y muestre por pantalla el día de la semana correspondiente. Controlar que el número se encuentre en el rango correcto, si no es así, informar un error. Por ejemplo, si el número es 2 el día es martes.
"""



"""### **Ejercicio 19**

Las y los alumnas y alumnos de un curso se han dividido en dos grupos A y B de acuerdo al género y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su inicial y género, y muestre por pantalla el grupo que le corresponde.
"""



"""### **Ejercicio 20**

Escribir un programa para una empresa que tiene salas de juegos para todas las edades y quiere calcular de forma automática el precio que debe cobrar a sus clientes por entrar. El programa debe preguntar al usuario la edad del cliente y mostrar el precio de la entrada. Si el cliente es menor de 4 años puede entrar gratis, si tiene entre 4 y 18 años debe pagar \$5 y si es mayor de 18 años, \$10.
"""



"""### **Ejercicio 21**

Mostrar por pantalla todos los números enteros entre 1 y 100, hacerlo usando un bucle while y tambien con un bucle for.
"""



"""### **Ejercicio 22**

Escribir un programa que pida al usuario dos números enteros e imprima todos los números enteros entre ellos.
"""



"""### **Ejercicio 23**

Escribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla en líneas distintas el nombre del usuario tantas veces como el número introducido.
"""



"""###**Ejercicio 24**

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla todos los números impares desde 1 hasta ese número.
"""



"""### **Ejercicio 25**

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo, de altura igual al número introducido.

Por ejemplo, si el usuario ingresa el numero 4:

\*

\* *

\* * *

\* * * * 
"""



"""### **Ejercicio 26**

Escribir un programa que imprima por pantalla todas las fichas del domino, una por línea, sin repetir.
"""



"""###**Ejercicio 27**

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo.

Si el usuario ingresa el numero 5:

1             

3 1           

5 3 1         

7 5 3 1       

9 7 5 3 1     
"""



"""
### **Ejercicio 28**

Escribir un programa que pida un número natural **N** al usuario e imprima por pantalla la suma de los números naturales de 1 hasta **N**. 

Por ejemplo para **N = 5**, la salida debe ser:

1 + 2 + 3 + 4 + 5 = 15"""



"""### **Ejercicio 29**

Construir un programa que lea un número natural **N** y calcule la suma de los primeros **N** números pares.
"""



"""### **Ejercicio 30**

Escribir un programa que recibe como entrada desde el usuario dos números enteros e informa por pantalla todos los números pares entre ellos.
"""



"""### **Ejercicio 31**

Escribir un programa que pida un número entero y muestre por pantalla la cantidad de cifras de dicho número.
"""



"""### **Ejercicio 32**

Escribir un programa que pida un número entero e informe si dicho numero es primo o no primo. 
"""

